services:
  db:
    image: mysql
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    container_name: mysql
    ports:
      - "3306:3306"
    env_file:
      - db.env
    volumes:
      - /Users/ljh/Docume/nts/springStudy/mysql/mysql:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - app.env
    depends_on:
      - db
